"use client";

import React from 'react';
import Image from 'next/image';
import { ArrowLeft, Github } from 'lucide-react';

interface AboutViewProps {
  onBack: () => void;
}

export const AboutView = ({ onBack }: AboutViewProps) => {
  return (
    <div className="min-h-screen bg-bg-deep text-text-secondary font-sans selection:bg-coral-mid/30">
      <header className="bg-brand-black sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 h-[72px] flex items-center justify-between">
          <div className="flex items-center gap-8">
            <div className="flex items-center gap-2 cursor-pointer" onClick={onBack}>
              <div className="relative h-12 w-12">
                <Image 
                  src="/logo-transparent.png" 
                  alt="ClawBench Logo" 
                  fill
                  className="object-contain"
                  referrerPolicy="no-referrer"
                />
              </div>
              <div className="flex flex-col justify-center items-start">
                <span className="text-xl font-black text-white tracking-tighter leading-none">ClawBench</span>
                <span className="text-white/60 text-[10px] font-bold uppercase tracking-widest mt-1 leading-none">LLM Agent Benchmark</span>
              </div>
            </div>
          </div>

          <div className="flex items-center gap-6">
            <a href="#" onClick={(e) => { e.preventDefault(); }} className="text-sm font-bold text-brand-red uppercase tracking-widest">About</a>
            <a 
              href="https://github.com/clawbench" 
              target="_blank" 
              rel="noopener noreferrer"
              className="flex items-center gap-2 bg-white/10 hover:bg-white/20 border border-white/10 px-4 py-2 rounded-full text-sm font-bold text-white transition-all"
            >
              <Github className="w-4 h-4" />
              <span>GitHub</span>
            </a>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-12">
        <button 
          onClick={onBack}
          className="flex items-center gap-2 text-text-muted hover:text-brand-red transition-colors mb-8 group cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
          <span className="text-sm font-bold uppercase tracking-widest">Back to Dashboard</span>
        </button>

        <h1 className="text-5xl font-black tracking-tighter text-text-primary mb-12">About ClawBench</h1>
        
        <div className="space-y-12 text-lg leading-relaxed text-text-secondary">
          <section>
            <p className="mb-4">
              ClawBench is an LLM Agents evaluation benchmark designed to address the limitations of traditional &quot;QA-style&quot; leaderboards, which often fail to reflect a model&apos;s true performance in complex workflows. We have constructed an isolated sandbox environment featuring 30 advanced tasks that comprehensively cover 5 core business scenarios: Office Collaboration, Information Retrieval, Content Creation, Data Processing, and Software Engineering.
            </p>
            <p>
              Unlike single-dimensional Q&A tests, ClawBench intentionally embeds real-world engineering challenges such as &quot;naming inconsistencies,&quot; &quot;missing directories,&quot; and &quot;date traps.&quot; By pioneering a Hybrid Grading mechanism, ClawBench not only precisely audits the code and data generated by Agents using Dynamic Ground Truth but also deeply evaluates the rigor of their business logic and compliance awareness. This provides the most credible capability metrics for the real-world deployment of LLM Agents.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary mb-4">Contact Us</h2>
            <p>
              Have questions, suggestions, or want to collaborate? Reach out to us through our GitHub repository.
            </p>
            <div className="mt-6">
              <a 
                href="https://github.com/clawbench" 
                target="_blank" 
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 bg-brand-black hover:bg-brand-red text-white px-6 py-3 rounded-full font-bold transition-all"
              >
                <Github className="w-5 h-5" />
                Visit our GitHub
              </a>
            </div>
          </section>
        </div>
      </main>

      <footer className="bg-bg-surface border-t border-border-subtle py-12 mt-20">
        <div className="max-w-7xl mx-auto px-6">
          <div className="flex flex-col md:flex-row justify-between items-center gap-8">
            <div className="flex items-center gap-2 cursor-pointer" onClick={onBack}>
              <div className="relative h-12 w-12">
                <Image 
                  src="/logo-transparent.png" 
                  alt="ClawBench Logo" 
                  fill
                  className="object-contain"
                  referrerPolicy="no-referrer"
                />
              </div>
              <div className="flex flex-col justify-center items-start">
                <span className="text-lg font-black text-text-primary tracking-tighter leading-none">ClawBench</span>
                <span className="text-text-muted text-[10px] font-bold uppercase tracking-widest mt-1 leading-none">LLM Agent Benchmark</span>
              </div>
            </div>
            <div className="text-text-muted text-sm font-medium">
              © 2026 ClawBench. All rights reserved.
            </div>
            <div className="flex items-center gap-6">
              <a href="#" onClick={(e) => { e.preventDefault(); }} className="text-brand-red text-sm font-bold uppercase tracking-widest">About</a>
              <a href="https://github.com/clawbench" target="_blank" rel="noopener noreferrer" className="text-text-muted hover:text-text-primary transition-colors"><Github className="w-5 h-5" /></a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};
